/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,jsx,ts,tsx}',
    './src/components/**/*.{js,jsx,ts,tsx}',
    './src/layouts/**/*.{js,jsx,ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#154212',
        'on-primary': '#ffffff',
        'primary-container': '#2d5a27',
        'on-primary-container': '#9dd090',
        'primary-fixed': '#bcf0ae',
        'primary-fixed-dim': '#a1d494',
        'on-primary-fixed': '#002201',
        'on-primary-fixed-variant': '#23501e',
        'inverse-primary': '#a1d494',
        'surface-tint': '#3b6934',
        'secondary': '#5c5f60',
        'on-secondary': '#ffffff',
        'secondary-container': '#e1e3e4',
        'on-secondary-container': '#626566',
        'secondary-fixed': '#e1e3e4',
        'secondary-fixed-dim': '#c5c7c8',
        'on-secondary-fixed': '#191c1d',
        'on-secondary-fixed-variant': '#454748',
        'tertiary': '#60233e',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#7c3a55',
        'on-tertiary-container': '#ffaac8',
        'tertiary-fixed': '#ffd9e4',
        'tertiary-fixed-dim': '#ffb0cc',
        'on-tertiary-fixed': '#3b0520',
        'on-tertiary-fixed-variant': '#71314c',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#f9f9f9',
        'on-background': '#1a1c1c',
        'surface': '#f9f9f9',
        'on-surface': '#1a1c1c',
        'surface-variant': '#e2e2e2',
        'on-surface-variant': '#42493e',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f4',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'outline': '#72796e',
        'outline-variant': '#c2c9bb',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f0f1f1',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '48px',
        'base': '4px',
        'grid-gutter': '20px',
        'container-margin': '32px',
      },
      fontFamily: {
        'h1': ['Montserrat', 'sans-serif'],
        'h2': ['Montserrat', 'sans-serif'],
        'h3': ['Montserrat', 'sans-serif'],
        'button': ['Montserrat', 'sans-serif'],
        'label-caps': ['Montserrat', 'sans-serif'],
        'body-lg': ['Be Vietnam Pro', 'sans-serif'],
        'body-md': ['Be Vietnam Pro', 'sans-serif'],
      },
      fontSize: {
        'h1': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h2': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'h3': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'button': ['14px', { lineHeight: '1', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
