// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
<<<<<<< HEAD
import { HelmetProvider } from 'C:/Users/Admin/Desktop/huy/web sân bóng/Football-Management/Frontend/node_modules/@umijs/renderer-react';
=======
import { HelmetProvider } from 'C:/Users/T14s Gen 3/Downloads/Football Pitches Management System/Football-Management/Frontend/node_modules/@umijs/renderer-react';
>>>>>>> a6c83e67f96e55853ede099d9ded7afa62ca084d
import { context } from './helmetContext';

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context }, container);
}
