// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
<<<<<<< HEAD
import model_1 from 'C:/Users/Admin/Desktop/huy/web sân bóng/Football-Management/Frontend/src/.umi-production/plugin-initialState/@@initialState';
=======
import model_1 from 'C:/Users/T14s Gen 3/Downloads/Football Pitches Management System/Football-Management/Frontend/src/.umi-production/plugin-initialState/@@initialState';
>>>>>>> a6c83e67f96e55853ede099d9ded7afa62ca084d

export const models = {
model_1: { namespace: '@@initialState', model: model_1 },
} as const
