// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'D:/PTIT/TH_Laptrinhweb/Football-Management/Frontend/src/models/adminBookings';
import model_2 from 'D:/PTIT/TH_Laptrinhweb/Football-Management/Frontend/src/models/adminForum';
import model_3 from 'D:/PTIT/TH_Laptrinhweb/Football-Management/Frontend/src/models/adminPitches';
import model_4 from 'D:/PTIT/TH_Laptrinhweb/Football-Management/Frontend/src/models/adminServices';
import model_5 from 'D:/PTIT/TH_Laptrinhweb/Football-Management/Frontend/src/models/adminUsers';
import model_6 from 'D:/PTIT/TH_Laptrinhweb/Football-Management/Frontend/src/models/auth';
import model_7 from 'D:/PTIT/TH_Laptrinhweb/Football-Management/Frontend/src/.umi-production/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'adminBookings', model: model_1 },
model_2: { namespace: 'adminForum', model: model_2 },
model_3: { namespace: 'adminPitches', model: model_3 },
model_4: { namespace: 'adminServices', model: model_4 },
model_5: { namespace: 'adminUsers', model: model_5 },
model_6: { namespace: 'auth', model: model_6 },
model_7: { namespace: '@@initialState', model: model_7 },
} as const
