// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/auth/login","id":"1"},"2":{"path":"/auth/login","id":"2"},"3":{"path":"/auth/signup","id":"3"},"4":{"path":"/","id":"4"},"5":{"path":"/user/dashboard","parentId":"4","id":"5"},"6":{"path":"/user/profile","parentId":"4","id":"6"},"7":{"path":"/user/bookings","parentId":"4","id":"7"},"8":{"path":"/user/notifications","parentId":"4","id":"8"},"9":{"path":"/pitches","parentId":"4","id":"9"},"10":{"path":"/booking/availability","parentId":"4","id":"10"},"11":{"path":"/admin","id":"11"},"12":{"path":"/admin/dashboard","parentId":"11","id":"12"},"13":{"path":"/admin/requests","parentId":"11","id":"13"},"14":{"path":"/admin/pitches","parentId":"11","id":"14"},"15":{"path":"/admin/pricing","parentId":"11","id":"15"},"16":{"path":"/admin/customers","parentId":"11","id":"16"},"17":{"path":"/admin/finance","parentId":"11","id":"17"},"18":{"path":"/admin/services","parentId":"11","id":"18"},"19":{"path":"/admin/notifications","parentId":"11","id":"19"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__auth__login__index" */'@/pages/auth/login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__auth__signup__index" */'@/pages/auth/signup/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "layouts__UserLayout" */'@/layouts/UserLayout.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__user__dashboard__index" */'@/pages/user/dashboard/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__user__profile__index" */'@/pages/user/profile/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__user__bookings__index" */'@/pages/user/bookings/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__user__notifications__index" */'@/pages/user/notifications/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__pitches__index" */'@/pages/pitches/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__booking__availability__index" */'@/pages/booking/availability/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "layouts__AdminLayout" */'@/layouts/AdminLayout.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__admin__dashboard__index" */'@/pages/admin/dashboard/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__admin__requests__index" */'@/pages/admin/requests/index.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__admin__pitches__index" */'@/pages/admin/pitches/index.tsx')),
'15': React.lazy(() => import(/* webpackChunkName: "p__admin__pricing__index" */'@/pages/admin/pricing/index.tsx')),
'16': React.lazy(() => import(/* webpackChunkName: "p__admin__customers__index" */'@/pages/admin/customers/index.tsx')),
'17': React.lazy(() => import(/* webpackChunkName: "p__admin__finance__index" */'@/pages/admin/finance/index.tsx')),
'18': React.lazy(() => import(/* webpackChunkName: "p__admin__services__index" */'@/pages/admin/services/index.tsx')),
'19': React.lazy(() => import(/* webpackChunkName: "p__admin__notifications__index" */'@/pages/admin/notifications/index.tsx')),
},
  };
}
